---
- name: promote server to a Domain Controller
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp

  tasks:
  - name: create domain controllers
    win_domain:
      dns_domain_name: "{{ domain_name }}"
      safe_mode_password: "{{ password }}""
    register: domain_result

  - name: reboot after creating domain
    win_reboot:
    when: domain_result.reboot_required
