---
# This playbook installs and enables IIS on Windows hosts
# using DSC (Define State Configuration)
- name: install IIS using DSC
  hosts: all
  vars_files:
    - winrm_vars.yml

  tasks:
  - name: install xWebAdministration module
    win_psmodule:
      name: xWebAdministration
      state: present

  - name: install IIS features that are required
    win_dsc:
      resource_name: WindowsFeature
      Name: '{{item}}'
      Ensure: Present
    with_items:
    - Web-Server
    - Web-Asp-Net45

  - name: setup web content
    win_dsc:
      resource_name: File
      DestinationPath: C:\inetpub\IISSite\index.html
      Type: File
      Contents: |
        <html>
        <head><title>IIS Site</title></head>
        <body>This is the body</body>
        </html>
      Ensure: present

  - name: create new website
    win_dsc:
      resource_name: xWebsite
      Name: NewIISSite
      State: Started
      PhysicalPath: C:\inetpub\IISSite\index.html
      BindingInfo:
      - Protocol: https
        Port: 8443
        CertificateStoreName: My
        CertificateThumbprint: C676A89018C4D5902353545343634F35E6B3A659
        HostName: DSCTest
        IPAddress: '*'
        SSLFlags: "1"
      - Protocol: http
        Port: 8080
        IPAddress: '*'
      AuthenticationInfo:
        Anonymous: no
        Basic: yes
        Digest: no
        Windows: yes

  - name: Enable firewall
    win_firewall:
      state: enabled

  - name: Firewall rule to allow http on TCP port 80
    win_firewall_rule:
      name: http
      localport: 80
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  - name: Firewall rule to allow https on TCP port 443
    win_firewall_rule:
      name: http
      localport: 443
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
