---
- name: configure the Windows Server
#  hosts: "{{ hostname }}"
  hosts: all
  vars_files:
    - winrm.yml

  tasks:
  - name: install common packages
    win_chocolatey:
      name: '{{item}}'
      state: present
    with_items:
    - sysinternals
    - notepadplusplus
    - googlechrome
    - git
