---
- name: configure the Windows Server
#  hosts: "{{ hostname }}"
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
  tasks:
  - name: install common packages
    win_chocolatey:
      name: '{{item}}'
      state: present
    with_items:
    - sysinternals
    - notepadplusplus
    - googlechrome
    - git
