---
- name: Check for updates and install them
  hosts: all
  vars_files:
    - winrm_vars.yml

  tasks:
  - win_updates:
      category_names: CriticalUpdates
    register: wuout
  - win_reboot:
    when: wuout.reboot_required
