---
- name: Check for updates and install them
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
  tasks:
  - win_updates:
      category_names: CriticalUpdates
    register: wuout
  - win_reboot:
    when: wuout.reboot_required
