---
# this playbook promotes a windows server to a domain controller
# It depend on external (extra) vars to supply the domain name and the safe_mode_password
- name: promote server to a Domain Controller
  hosts: all
  vars_files:
    - winrm_vars.yml

  tasks:
  - name: create domain controllers
    win_domain:
      dns_domain_name: "{{ domain_name }}"
      safe_mode_password: "{{ password }}"
    register: domain_result

  - name: reboot after creating domain
    win_reboot:
    when: domain_result.reboot_required
